[tool.briefcase]
project_name = "AVA"
bundle = "tk.unknownts"
version = "0.0.1"
url = "https://unknownts.tk/ava_app"
license = "GNU General Public License v3 or later (GPLv3+)"
author = 'Zane Reick'
author_email = "zane@unknownts.tk"

[tool.briefcase.app.ava_app]
formal_name = "AVA"
description = "An adVanced Assistant"
icon = "src/ava_app/resources/ava_app"
sources = ['src/ava_app']
requires = []


[tool.briefcase.app.ava_app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.ava_app.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.ava_app.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.ava_app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.ava_app.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
