[tool.briefcase]
project_name = "AVA"
bundle = "tk.unknownts"
version = "0.0.2"
url = "https://unknownts.tk/ava_app"
license = "GNU General Public License v3 or later (GPLv3+)"
author = 'Zane Reick'
author_email = "zane@unknownts.tk"

[tool.briefcase.app.ava_app]
formal_name = "AVA"
description = "An adVanced Assistant"
icon = "src/ava_app/resources/ava_app"
sources = ['src/ava_app']
requires = [
    "beautifulsoup4==4.9.3",
    "certifi==2020.12.5",
    "chardet==3.0.4",
    "idna==2.10",
    "pocketsphinx>=0.1.15",
    "pyttsx3>=2.90",
    "requests>=2.25.0",
    "soupsieve==2.0.1",
    "SpeechRecognition>=3.8.1",
    "urllib3>=1.26.2",
    "wikipedia>=1.4.0",
]


[tool.briefcase.app.ava_app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
    "beautifulsoup4==4.9.3",
    "certifi==2020.12.5",
    "chardet==3.0.4",
    "idna==2.10",
    "pocketsphinx>=0.1.15",
    "pyttsx3>=2.90",
    "requests>=2.25.0",
    "soupsieve==2.0.1",
    "SpeechRecognition>=3.8.1",
    "urllib3>=1.26.2",
    "wikipedia>=1.4.0",
]

[tool.briefcase.app.ava_app.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
    "beautifulsoup4==4.9.3",
    "certifi==2020.12.5",
    "chardet==3.0.4",
    "idna==2.10",
    "pocketsphinx>=0.1.15",
    "pyttsx3>=2.90",
    "requests>=2.25.0",
    "soupsieve==2.0.1",
    "SpeechRecognition>=3.8.1",
    "urllib3>=1.26.2",
    "wikipedia>=1.4.0",
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.ava_app.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
    "beautifulsoup4==4.9.3",
    "certifi==2020.12.5",
    "chardet==3.0.4",
    "idna==2.10",
    "pocketsphinx>=0.1.15",
    "pyttsx3>=2.90",
    "requests>=2.25.0",
    "soupsieve==2.0.1",
    "SpeechRecognition>=3.8.1",
    "urllib3>=1.26.2",
    "wikipedia>=1.4.0",
]

# Mobile deployments
[tool.briefcase.app.ava_app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.ava_app.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
